[node-1]
ip-10-0-0-218.ap-southeast-1.compute.internal

[node-2]
ip-10-0-0-199.ap-southeast-1.compute.internal

[node-3]
ip-10-0-0-221.ap-southeast-1.compute.internal

[node-4]
ip-10-0-0-198.ap-southeast-1.compute.internal

[zookeeper-1]
ip-10-0-0-196.ap-southeast-1.compute.internal

[zookeeper-2]
ip-10-0-0-238.ap-southeast-1.compute.internal

[zookeeper-3]
ip-10-0-0-233.ap-southeast-1.compute.internal

[client]
ip-10-0-0-232.ap-southeast-1.compute.internal

[broker-group-1:children]
node-1
node-2

[broker-group-2:children]
node-3
node-4

[dc-1:children]
broker-group-1

[dc-2:children]
broker-group-2
