---
- name: Create Dirs for Copied Files
  file:
    path: "{{ item.destination_path | dirname }}"
    state: directory
    mode: 0750
  loop: "{{ copy_files }}"

- name: Copy Files
  copy:
    src: "{{ item.source_path }}"
    dest: "{{ item.destination_path }}"
    mode: 0640
  loop: "{{ copy_files }}"
