---
- meta: flush_handlers

- name: Check if Service Exists
  stat: path=/etc/systemd/system/confluent-server.service.d
  register: is_broker

- name: Starting {{process_name}}
  systemd: 
    daemon_reload: true
    name: "{{process_name}}"
    enabled: true
    state: started
  when: (('confluent-server' in process_name) and (is_broker.stat.exists)) or ('confluent-zookeeper' in process_name)

