---
- meta: flush_handlers

- name: Check if Service Exists
  stat: path=/etc/systemd/system/confluent-server.service.d
  register: is_broker

- name: Starting {{process_name}}
  systemd: 
    daemon_reload: true
    name: "{{process_name}}"
    enabled: true
    state: started
  when: (('confluent-server' in process_name) and (is_broker.stat.exists)) or ('confluent-zookeeper' in process_name)

  #shell: "sudo systemctl start {{process_name}}"

#- name: Check if Service Exists
#  stat: path=/etc/systemd/system/confluent-server.service.d
#  register: is_broker
#
#- name: Wait for Under Replicated Partitions Metric to return 200
#  uri:
#    url: "{{ 'https' if kafka_broker_jolokia_ssl_enabled|bool else 'http' }}://{{inventory_hostname}}:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
#    validate_certs: false
#    return_content: true
#    status_code: 200
#  register: urp_result1
#  until: urp_result1.status == 200
#  retries: 10
#  delay: 5
#  ignore_errors: true
#  when: 
#  - is_broker.stat.exists
#  - process_name == 'confluent-server.service'
#
#- name: Wait for Under Replicated Partitions Metric to return Data
#  uri:
#    url: "{{ 'https' if kafka_broker_jolokia_ssl_enabled|bool else 'http' }}://{{inventory_hostname}}:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
#    validate_certs: false
#    return_content: true
#    status_code: 200
#  register: urp_result2
#  until: urp_result2['json']['value'] is defined
#  retries: 10
#  delay: 5
#  when:
#    - is_broker.stat.exists
#    - process_name == 'confluent-server.service'
#    # Skip if previous check failed. If URP check was skipped, defaulting failed to False
#    - not urp_result1.failed|default(False)
#  ignore_errors: true
#
#- name: Wait for Under Replicated Partitions Metric to equal Zero
#  uri:
#    url: "{{ 'https' if kafka_broker_jolokia_ssl_enabled|bool else 'http' }}://{{inventory_hostname}}:{{kafka_broker_jolokia_port}}/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
#    validate_certs: false
#    return_content: true
#    status_code: 200
#  register: urp_result3
#  until: urp_result3['json']['value']['Value'] == 0
#  retries: 10
#  delay: 5
#  when:
#    - is_broker.stat.exists
#    - process_name == 'confluent-server.service'
#    # Skip if either previous checks failed. If URP check was skipped, defaulting failed to False
#    - not urp_result1.failed|default(False) and not urp_result2.failed|default(False)
#  ignore_errors: true
